### ISSUE TITLE
No ban appeals

### ISSUE THREAD

**Issue by elementgermanium** [hjc/tpp#4]
I was banned forever and I don't know why, twitch username elementgermanium. Please unban me! It was nearly 6 months ago and I was never told why I was banned. At least tell me why I was banned, or if possible, unban me.

**Comment by hjc** [comment]
This repo name is a little misleading. This is not for the actual Twitch Plays Pokemon, it is for the fan site: http://www.tppkmn.net that I maintain in my free time.

I cannot unban you. Closing issue. Soz m8.
